"""
Export the ingestion contract and a sample synthetic dataset.

Produces three things:
  1. JSON Schema for each of the seven entities, for MOIL's mapping work.
  2. Sample CSVs of generated data, one per entity.
  3. A long-horizon annual production series for the dashboard's trend view,
     replacing a hand-written table that attributed invented figures to MOIL,
     IBM, GSI and IMD by name.

Run:  python -m app.ingestion.export
"""
from __future__ import annotations

import csv
import json
import math
from datetime import date
from pathlib import Path

import numpy as np

from app.ingestion.generator import (
    ANNUAL_TOTAL_TONNES,
    DEFAULT_SEED,
    GENERATOR_SOURCE,
    MINES,
    TREND_PER_YEAR,
    generate_all,
)
from app.ingestion.schemas import CONTRACT_VERSION, all_json_schemas

REPO = Path(__file__).resolve().parents[3]
SCHEMA_DIR = REPO / "docs" / "schemas"
SAMPLE_DIR = REPO / "data" / "synthetic"
FRONTEND_DATA = REPO / "frontend" / "src" / "data"

ENTITY_ORDER = [
    "borehole",
    "assay",
    "lithology",
    "production_by_mine_grade_period",
    "equipment_event",
    "blast_record",
    "plan_target",
]


def export_schemas() -> Path:
    SCHEMA_DIR.mkdir(parents=True, exist_ok=True)
    bundle = all_json_schemas()
    out = SCHEMA_DIR / "ingestion-contract.schema.json"
    out.write_text(json.dumps(bundle, indent=2) + "\n")
    for name, schema in bundle["entities"].items():
        (SCHEMA_DIR / f"{name}.schema.json").write_text(json.dumps(schema, indent=2) + "\n")
    return out


def export_samples(rows_per_entity: int = 500, seed: int = DEFAULT_SEED) -> dict[str, int]:
    """Write a bounded sample per entity — enough to validate a mapping."""
    SAMPLE_DIR.mkdir(parents=True, exist_ok=True)
    data = generate_all(seed=seed)
    counts: dict[str, int] = {}
    for entity in ENTITY_ORDER:
        rows = data[entity][:rows_per_entity]
        if not rows:
            continue
        path = SAMPLE_DIR / f"{entity}.sample.csv"
        dicts = [r.model_dump(mode="json") for r in rows]
        with path.open("w", newline="") as fh:
            w = csv.DictWriter(fh, fieldnames=list(dicts[0].keys()))
            w.writeheader()
            w.writerows(dicts)
        counts[entity] = len(rows)
    (SAMPLE_DIR / "README.md").write_text(
        f"""# Sample synthetic data

Generated by `{GENERATOR_SOURCE}` (seed `{seed}`), contract `{CONTRACT_VERSION}`.

**Every row is synthetic.** `is_synthetic` is `true` throughout. These are not
MOIL's figures and must not be presented as measurements of MOIL's operations.
See `docs/INGESTION_CONTRACT.md`.

Regenerate with:

```bash
cd backend && python -m app.ingestion.export
```

| Entity | Sample rows |
|---|---|
"""
        + "\n".join(f"| `{k}` | {v:,} |" for k, v in counts.items())
        + "\n"
    )
    return counts


def export_annual_history(
    start_year: int = 1977, end_year: int = 2026, seed: int = DEFAULT_SEED
) -> Path:
    """
    A long-horizon annual series for the dashboard trend view.

    The table this replaces carried per-year drill-hole counts, "UNFC 111 proved
    reserves" and monsoon rainfall attributed to MOIL Annual Reports, the IBM
    Indian Minerals Yearbook, GSI and IMD. Those numbers were not taken from
    those sources. This series is generated from the same calibrated model as
    the rest of the contract, is flagged synthetic, and names no source it does
    not have.

    Production is back-projected from the present-day anchor using the model's
    trend rate, so early years are lower — the shape is a modelling assumption,
    not a record of what MOIL produced.
    """
    rng = np.random.default_rng(seed + 909)
    records = []
    for year in range(start_year, end_year + 1):
        years_from_anchor = year - 2025
        trend = (1.0 + TREND_PER_YEAR) ** years_from_anchor
        shock = float(rng.normal(1.0, 0.055))
        production = ANNUAL_TOTAL_TONNES * trend * shock

        # Monsoon total for the year, from the same seasonal model.
        monsoon = float(np.clip(rng.normal(1180, 190), 520, 2100))
        # Weighted mean Mn grade, drifting slowly downward as higher-grade
        # ground is worked out — an assumption, stated as one.
        grade = float(np.clip(43.5 - 0.035 * (year - start_year) + rng.normal(0, 0.45), 33.0, 48.0))
        boreholes = int(np.clip(rng.normal(180 + 2.2 * (year - start_year), 35), 20, 600))
        resource_base = float(np.clip(
            48_000_000 * (1.0 + 0.008 * (year - start_year)) * float(rng.normal(1.0, 0.03)),
            20_000_000, 90_000_000,
        ))

        records.append({
            "year": year,
            "totalProductionTonnes": round(production),
            "avgMnGradePct": round(grade, 2),
            "syntheticBoreholeCount": boreholes,
            "monsoonRainfallMm": round(monsoon),
            "indicativeResourceBaseTonnes": round(resource_base),
            "gradeType": (
                "Ferro-manganese dominant" if grade >= 42
                else "Silico-manganese dominant" if grade >= 37
                else "Blast-furnace / blending dominant"
            ),
            "is_synthetic": True,
        })

    payload = {
        "contract_version": CONTRACT_VERSION,
        "generator": GENERATOR_SOURCE,
        "seed": seed,
        "is_synthetic": True,
        "notice": (
            "Synthetic illustrative series. Generated from a model anchored to "
            "MOIL's published annual production scale (~1.1-1.3 Mt/yr). It is "
            "NOT taken from MOIL Annual Reports, the IBM Indian Minerals "
            "Yearbook, GSI Bhukosh or IMD, and must not be presented as such. "
            "`indicativeResourceBaseTonnes` is not a UNFC or statutory reserve "
            "figure (PRD 2.4)."
        ),
        "mines_modelled": [m.name for m in MINES],
        "records": records,
    }
    FRONTEND_DATA.mkdir(parents=True, exist_ok=True)
    out = FRONTEND_DATA / "synthetic-history.json"
    out.write_text(json.dumps(payload, indent=2) + "\n")
    return out


def main() -> None:
    schema_path = export_schemas()
    print(f"schemas  -> {schema_path.relative_to(REPO)} (+ {len(ENTITY_ORDER)} per-entity files)")
    counts = export_samples()
    for k, v in counts.items():
        print(f"sample   -> data/synthetic/{k}.sample.csv ({v:,} rows)")
    hist = export_annual_history()
    print(f"history  -> {hist.relative_to(REPO)}")


if __name__ == "__main__":
    main()
