import { NextRequest, NextResponse } from 'next/server'
import { MineIdParamSchema, validateReplayNonce } from '@/lib/security'
import {
  Envelope,
  dataIntegrity,
  derived,
  measured,
  reference,
  synthetic,
} from '@/lib/provenance'
import { SYNTHETIC_CALIBRATION, mineStream, operatingDay, round } from '@/lib/synthetic'
import { fetchSentinel2Scenes, STACScene } from '@/lib/stac'

/**
 * Mine telemetry endpoint.
 *
 * Integrity contract (see docs/INTEGRITY.md):
 *   - Weather is MEASURED from Open-Meteo when the call succeeds; on failure the
 *     response degrades to SYNTHETIC and says so.
 *   - Operational figures (downtime, blasting readiness, production rates) are
 *     SYNTHETIC — MOIL operational data is proprietary. They are generated by a
 *     seeded model so identical requests return identical values.
 *   - Risk and shortfall are DERIVED: an explicit, documented arithmetic model
 *     over the inputs above. The attribution returned is an exact additive
 *     decomposition of that model — it is not SHAP and is not labelled as such.
 *   - Scene metadata is a real STAC query against Earth Search. If the query
 *     fails the list is empty; scene identifiers are never fabricated.
 */

const MODEL_VERSION = 'nakshatra-drag-model-v1'
const ATTRIBUTION_VERSION = 'additive-driver-attribution-v1'

interface MineRecord {
  id: string
  numericId: number
  name: string
  code: string
  state: string
  lat: number
  lng: number
  zone: string
  targetTonnes: number
  currentProduction: number
}

const MINES: Record<number, MineRecord> = {
  1: { id: 'balaghat', numericId: 1, name: 'Balaghat', code: 'MOIL-BAL-01', state: 'MP', lat: 21.83, lng: 80.19, zone: 'Central India', targetTonnes: 18000, currentProduction: 16800 },
  2: { id: 'bharweli', numericId: 2, name: 'Bharweli', code: 'MOIL-BHR-02', state: 'MP', lat: 21.86, lng: 80.26, zone: 'Central India', targetTonnes: 14500, currentProduction: 12200 },
  3: { id: 'ukwa', numericId: 3, name: 'Ukwa', code: 'MOIL-UKW-03', state: 'MP', lat: 21.93, lng: 80.52, zone: 'Central India', targetTonnes: 9800, currentProduction: 8900 },
  4: { id: 'tirodi', numericId: 4, name: 'Tirodi', code: 'MOIL-TIR-04', state: 'MP', lat: 22.16, lng: 79.68, zone: 'Central India', targetTonnes: 11200, currentProduction: 10100 },
  5: { id: 'dongri-buzurg', numericId: 5, name: 'Dongri Buzurg', code: 'MOIL-DON-05', state: 'MH', lat: 20.99, lng: 79.34, zone: 'Western Belt', targetTonnes: 12000, currentProduction: 11200 },
  6: { id: 'chikla', numericId: 6, name: 'Chikla', code: 'MOIL-CHK-06', state: 'MH', lat: 21.30, lng: 79.66, zone: 'Western Belt', targetTonnes: 10800, currentProduction: 9800 },
  7: { id: 'mansar', numericId: 7, name: 'Mansar', code: 'MOIL-MAN-07', state: 'MH', lat: 21.44, lng: 79.25, zone: 'Western Belt', targetTonnes: 12500, currentProduction: 11800 },
  8: { id: 'kandri', numericId: 8, name: 'Kandri', code: 'MOIL-KAN-08', state: 'MH', lat: 21.38, lng: 79.32, zone: 'Western Belt', targetTonnes: 9300, currentProduction: 8400 },
  9: { id: 'gumgaon', numericId: 9, name: 'Gumgaon', code: 'MOIL-GUM-09', state: 'MH', lat: 21.33, lng: 79.03, zone: 'Western Belt', targetTonnes: 10200, currentProduction: 9600 },
  10: { id: 'beldongri', numericId: 10, name: 'Beldongri', code: 'MOIL-BEL-10', state: 'MH', lat: 21.16, lng: 79.18, zone: 'Western Belt', targetTonnes: 8600, currentProduction: 7800 },
}

const MINE_SOURCE = 'MOIL public mine register (coordinates, lease names)'
const OPEN_METEO = 'Open-Meteo Forecast API v1'

interface WeatherReading {
  rainfall14d: number
  forecastRain3d: number
  precipRate: number
  tempC: number
  humidity: number
  soilMoisturePct: number
  live: boolean
  vintage: string
  failure: string | null
}

/**
 * Fetch weather from Open-Meteo.
 *
 * Correctness note: `past_days` and `forecast_days` are requested together and
 * the returned `daily.time` array is split on today's date. The previous
 * implementation summed the whole `daily` array (which silently included
 * forecast days) and called the result "past 14 days".
 */
async function fetchWeather(mine: MineRecord): Promise<WeatherReading> {
  const url =
    `https://api.open-meteo.com/v1/forecast?latitude=${mine.lat}&longitude=${mine.lng}` +
    `&current=temperature_2m,relative_humidity_2m,precipitation` +
    `&daily=precipitation_sum&past_days=14&forecast_days=4` +
    `&hourly=soil_moisture_0_to_1cm&timezone=UTC`

  try {
    const res = await fetch(url, {
      next: { revalidate: 3600 },
      signal: AbortSignal.timeout(8000),
    })
    if (!res.ok) throw new Error(`Open-Meteo responded ${res.status}`)
    const d = await res.json()

    const days: string[] = d?.daily?.time ?? []
    const sums: number[] = d?.daily?.precipitation_sum ?? []
    const today = new Date().toISOString().slice(0, 10)
    const todayIdx = days.findIndex((t) => t >= today)
    const splitAt = todayIdx === -1 ? days.length : todayIdx

    // Strictly past days only.
    const rainfall14d = sums.slice(Math.max(0, splitAt - 14), splitAt)
      .reduce((a, b) => a + (b || 0), 0)
    // Today + next 3 days.
    const forecastRain3d = sums.slice(splitAt, splitAt + 4)
      .reduce((a, b) => a + (b || 0), 0)

    const soilSeries: number[] = d?.hourly?.soil_moisture_0_to_1cm ?? []
    const soilNow = soilSeries.find((v) => typeof v === 'number')

    return {
      rainfall14d: round(rainfall14d, 1),
      forecastRain3d: round(forecastRain3d, 1),
      precipRate: round(d?.current?.precipitation ?? 0, 2),
      tempC: round(d?.current?.temperature_2m ?? 0, 1),
      humidity: Math.round(d?.current?.relative_humidity_2m ?? 0),
      // Open-Meteo returns volumetric soil moisture (m³/m³).
      soilMoisturePct: round((soilNow ?? 0.35) * 100, 1),
      live: true,
      vintage: d?.current?.time ? `${d.current.time}Z` : new Date().toISOString(),
      failure: null,
    }
  } catch (err: any) {
    // Degraded path: synthetic stand-ins, explicitly flagged by the caller.
    const s = mineStream(mine.id, 'weather-fallback')
    const monsoonBias = mine.state === 'MP' ? 1.15 : 1.0
    return {
      rainfall14d: round(s.boundedNormal(70 * monsoonBias, 25, 0, 320), 1),
      forecastRain3d: round(s.boundedNormal(14 * monsoonBias, 8, 0, 120), 1),
      precipRate: round(s.boundedNormal(0.3, 0.3, 0, 6), 2),
      tempC: round(s.boundedNormal(31, 3, 12, 48), 1),
      humidity: Math.round(s.boundedNormal(62, 12, 10, 100)),
      soilMoisturePct: round(s.boundedNormal(34, 7, 3, 60), 1),
      live: false,
      vintage: new Date().toISOString(),
      failure: err?.message || 'Open-Meteo unreachable',
    }
  }
}

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ mineId: string }> }
) {
  const nonceCheck = validateReplayNonce(request.headers.get('x-security-nonce'))
  if (!nonceCheck.valid) {
    return NextResponse.json({ error: nonceCheck.reason }, { status: 400 })
  }

  const resolvedParams = await params
  const parsedId = MineIdParamSchema.safeParse(resolvedParams.mineId)
  if (!parsedId.success) {
    return NextResponse.json({ error: 'Invalid Mine ID parameter' }, { status: 400 })
  }

  const idNum = parseInt(parsedId.data, 10) || 1
  const mine = MINES[idNum] || MINES[1]
  const day = operatingDay()

  // ---- Measured inputs -----------------------------------------------------
  const wx = await fetchWeather(mine)
  const wxKind = wx.live ? measured : synthetic
  const wxSource = wx.live ? OPEN_METEO : 'Synthetic weather fallback (upstream unavailable)'

  // ---- Synthetic operational inputs ---------------------------------------
  // MOIL does not publish per-mine equipment or blasting data. These are
  // generated deterministically and flagged; they are never called live.
  const ops = mineStream(mine.id, 'operations', day)
  const cal = SYNTHETIC_CALIBRATION
  const downtimeHours = round(
    ops.boundedNormal(
      cal.weekly_downtime_hours.mean,
      cal.weekly_downtime_hours.sd,
      cal.weekly_downtime_hours.min,
      cal.weekly_downtime_hours.max
    ),
    1
  )
  const equipmentAvailability = round(
    ops.boundedNormal(
      cal.equipment_availability_pct.mean,
      cal.equipment_availability_pct.sd,
      cal.equipment_availability_pct.min,
      cal.equipment_availability_pct.max
    ),
    1
  )
  const blastsThisWeek = Math.round(
    ops.boundedNormal(
      cal.blasts_per_week.mean,
      cal.blasts_per_week.sd,
      cal.blasts_per_week.min,
      cal.blasts_per_week.max
    )
  )
  const blastingReady = blastsThisWeek >= 6

  // ---- Derived model -------------------------------------------------------
  // Explicit, inspectable drag model. Each term is bounded and additive, so the
  // attribution below is an exact decomposition rather than an approximation.
  const weatherDrag = wx.rainfall14d > 60 ? Math.min(0.35, (wx.rainfall14d / 150) * 0.35) : 0.02
  const downtimeDrag = Math.min(0.30, (downtimeHours / 40) * 0.30)
  const blastingDrag = blastingReady ? 0.0 : 0.15
  const totalDrag = Math.min(0.55, weatherDrag + downtimeDrag + blastingDrag)
  const shortfallPct = round(totalDrag * 100, 1)

  const horizonDays = 14
  const dailyTarget = mine.targetTonnes / 30
  const plannedHorizon = Math.round(dailyTarget * horizonDays)
  const predictedHorizon = Math.round(plannedHorizon * (1 - totalDrag))
  const projectedShortfall = Math.max(0, plannedHorizon - predictedHorizon)

  const trajectory = Array.from({ length: horizonDays }, (_, i) => {
    const planned = Math.round(dailyTarget)
    const predicted = Math.round(planned * (1 - totalDrag))
    return {
      day_index: i + 1,
      date: `Day ${i + 1}`,
      planned_tonnes: planned,
      predicted_tonnes: predicted,
      shortfall_tonnes: Math.max(0, planned - predicted),
      efficiency_pct: round((1 - totalDrag) * 100, 1),
    }
  })

  const riskScore = round(Math.min(98, totalDrag * 160 + 8), 1)
  const isElevated = riskScore >= 55

  // ---- Real STAC query -----------------------------------------------------
  const stac = await fetchSentinel2Scenes(mine.lat, mine.lng)

  // ---- Response blocks (shapes preserved for existing UI consumers) --------
  const weather = {
    rainfall_14d_mm: wx.rainfall14d,
    soil_moisture_pct: wx.soilMoisturePct,
    land_surface_temp_c: wx.tempC,
    humidity_pct: wx.humidity,
    forecast_rain_next_3d_mm: wx.forecastRain3d,
    live_precipitation_rate_mm_hr: wx.precipRate,
    updated_at: wx.vintage,
    source: wx.live ? `${OPEN_METEO} (measured)` : 'SYNTHETIC FALLBACK — upstream unavailable',
    is_live: wx.live,
    is_synthetic: !wx.live,
  }

  const reserve = {
    mine_id: mine.numericId,
    category: 'DECISION_SUPPORT_ONLY',
    confidence_score: null,
    estimated_ore_grade: null,
    prospect_depth_m: null,
    recommendation:
      'Prospectivity scoring is not wired to this endpoint. Use the prospectivity model endpoint for map-cell scores with uncertainty.',
    // Deliberately empty: the previous hardcoded contributions and spectral
    // reflectance values were presented as model/satellite output but were not.
    feature_contributions: {},
    spectral_reflectance_bands: [],
    ndvi_trend_14d: [],
    note:
      'Not a UNFC/statutory reserve statement. Grade, depth and spectral values are omitted until real assay and Sentinel-2 band data are ingested.',
  }

  const forecast = {
    model: MODEL_VERSION,
    model_description:
      'Bounded additive drag model over measured rainfall and synthetic equipment/blasting inputs. Deterministic; no learned parameters.',
    horizon_days: horizonDays,
    total_planned_tonnes: plannedHorizon,
    total_predicted_tonnes: predictedHorizon,
    projected_shortfall_tonnes: projectedShortfall,
    shortfall_percentage: shortfallPct,
    risk_level: shortfallPct >= 20 ? 'CRITICAL' : shortfallPct >= 10 ? 'MODERATE' : 'NOMINAL',
    current_daily_rate_t: Math.round(dailyTarget * (1 - totalDrag)),
    drag_factors: {
      weather_drag_pct: round(weatherDrag * 100, 1),
      equipment_downtime_drag_pct: round(downtimeDrag * 100, 1),
      blasting_delay_drag_pct: round(blastingDrag * 100, 1),
    },
    trajectory,
  }

  const risk = {
    composite_risk_score: riskScore,
    risk_status: isElevated ? 'ELEVATED' : 'WATCH',
    rainfall_risk_score: round(Math.min(100, (weatherDrag / 0.35) * 100), 1),
    equipment_risk_score: round(Math.min(100, (downtimeDrag / 0.30) * 100), 1),
    blasting_risk_score: round((blastingDrag / 0.15) * 100, 1),
    stockpile_risk_score: null,
    predicted_shortfall_tonnes: projectedShortfall,
    live_downtime_hours: downtimeHours,
  }

  // Exact additive decomposition of `shortfallPct`. Named honestly: this is not
  // SHAP, and no SHAP library is used anywhere in this project.
  const attribution = {
    method: ATTRIBUTION_VERSION,
    method_description:
      'Exact additive decomposition of the drag model. Each term is the model coefficient applied to its input; the terms sum to the total shortfall percentage by construction. This is not a Shapley-value approximation.',
    composite_risk_score: riskScore,
    base_value: 0,
    waterfall_features: [
      {
        feature: `14-day rainfall (${wx.rainfall14d} mm, ${wx.live ? 'measured' : 'synthetic'})`,
        shap_value: round(weatherDrag * 100, 1),
        is_positive: weatherDrag > 0,
      },
      {
        feature: `Equipment downtime (${downtimeHours} h/week, synthetic)`,
        shap_value: round(downtimeDrag * 100, 1),
        is_positive: downtimeDrag > 0,
      },
      {
        feature: `Blasting readiness (${blastsThisWeek} blasts/week, synthetic)`,
        shap_value: round(blastingDrag * 100, 1),
        is_positive: blastingDrag > 0,
      },
    ],
    causal_chains: [
      {
        cause: `14-day rainfall ${wx.rainfall14d} mm`,
        intermediate: weatherDrag > 0.1 ? 'Haul road softening, increased cycle times' : 'Haulage conditions within normal range',
        impact: `${round(weatherDrag * 100, 1)}% of modelled production drag`,
        remedy: weatherDrag > 0.1 ? 'Haul road dressing and sump dewatering' : 'No weather action required',
      },
    ],
    primary_driver:
      weatherDrag >= downtimeDrag && weatherDrag >= blastingDrag
        ? 'Rainfall'
        : downtimeDrag >= blastingDrag
          ? 'Equipment downtime'
          : 'Blasting readiness',
  }

  const actions = buildActions(mine, { weatherDrag, downtimeDrag, blastingDrag, projectedShortfall })

  const audit = {
    satellite_source: stac.source,
    model_version: MODEL_VERSION,
    geologist_review_status: 'NOT_REVIEWED',
    last_evaluated: new Date().toISOString(),
    guardrail:
      'Decision-support output. Not a statutory reserve estimate; satellite inputs are surface/atmospheric only and do not detect subsurface ore.',
  }

  const provenance: Record<string, Envelope<any>> = {
    'weather.rainfall_14d_mm': wxKind(wx.rainfall14d, 'mm', wxSource, {
      vintage: wx.vintage,
      method: 'Sum of daily precipitation over the 14 calendar days before today.',
    }),
    'weather.forecast_rain_next_3d_mm': wxKind(wx.forecastRain3d, 'mm', wxSource, {
      vintage: wx.vintage,
      method: 'Sum of daily precipitation for today plus the next three forecast days.',
    }),
    'weather.land_surface_temp_c': wxKind(wx.tempC, '°C', wxSource, { vintage: wx.vintage }),
    'weather.humidity_pct': wxKind(wx.humidity, '%', wxSource, { vintage: wx.vintage }),
    'weather.soil_moisture_pct': wxKind(wx.soilMoisturePct, '%', wxSource, {
      vintage: wx.vintage,
      method: 'Volumetric soil moisture 0–1 cm, converted to percent.',
    }),
    'risk.live_downtime_hours': synthetic(downtimeHours, 'hours/week', SYNTHETIC_CALIBRATION.note, {
      model_version: 'synthetic-ops-v1',
      method: `Seeded draw, stream "${mine.id}|operations|${day}". Reproducible for a given mine and day.`,
    }),
    'operations.equipment_availability_pct': synthetic(
      equipmentAvailability,
      '%',
      SYNTHETIC_CALIBRATION.note,
      { model_version: 'synthetic-ops-v1' }
    ),
    'operations.blasts_this_week': synthetic(blastsThisWeek, 'count', SYNTHETIC_CALIBRATION.note, {
      model_version: 'synthetic-ops-v1',
    }),
    'forecast.shortfall_percentage': derived(shortfallPct, '%', 'Nakshatra-X drag model', {
      model_version: MODEL_VERSION,
      method:
        'min(0.55, weather_drag + downtime_drag + blasting_drag) × 100, over one measured and two synthetic inputs.',
      uncertainty: {
        plus_minus: 0,
        confidence: 0,
        basis:
          'Deterministic model with no fitted parameters — no statistical interval is defined. A backtested interval requires the Phase 4 forecaster.',
      },
    }),
    'forecast.total_planned_tonnes': reference(plannedHorizon, 'tonnes', MINE_SOURCE, {
      method: 'Monthly lease target ÷ 30 × 14-day horizon.',
    }),
    'risk.composite_risk_score': derived(riskScore, 'score 0-100', 'Nakshatra-X drag model', {
      model_version: MODEL_VERSION,
      method: 'min(98, total_drag × 160 + 8).',
    }),
    'mine.coordinates': reference(`${mine.lat}, ${mine.lng}`, 'lat,lng', MINE_SOURCE),
  }

  const integrity = dataIntegrity({
    containsSynthetic: true,
    liveOk: wx.live,
    degradedReason: wx.failure,
    stalenessSeconds: wx.live
      ? Math.max(0, Math.round((Date.now() - new Date(wx.vintage).getTime()) / 1000))
      : null,
  })

  return NextResponse.json({
    mine,
    weather,
    reserve,
    forecast,
    risk,
    // Field kept as `shap` for existing UI consumers; contents and naming are
    // now honest. See `attribution.method`.
    shap: attribution,
    attribution,
    actions,
    audit,
    stacScenes: stac.scenes as STACScene[],
    stac_status: stac.status,
    provenance,
    data_integrity: integrity,
    server_time: new Date().toISOString(),
  })
}

function buildActions(
  mine: MineRecord,
  ctx: { weatherDrag: number; downtimeDrag: number; blastingDrag: number; projectedShortfall: number }
) {
  const actions: Array<Record<string, any>> = []
  if (ctx.weatherDrag > 0.1) {
    actions.push({
      id: `act-${mine.id}-drainage`,
      title: 'Haul road dressing and sump dewatering',
      type: 'DRAINAGE',
      priority: ctx.weatherDrag > 0.25 ? 'CRITICAL' : 'HIGH',
      reason: `Rainfall accounts for ${round(ctx.weatherDrag * 100, 1)}% modelled production drag.`,
      impact: `Addresses the rainfall term; upper bound on recovery is ${Math.round(ctx.projectedShortfall * (ctx.weatherDrag / Math.max(ctx.weatherDrag + ctx.downtimeDrag + ctx.blastingDrag, 1e-9)))} t over the horizon.`,
      status: 'PROPOSED',
      basis: 'Rule-based: triggered when the weather drag term exceeds 0.10.',
    })
  }
  if (ctx.downtimeDrag > 0.1) {
    actions.push({
      id: `act-${mine.id}-maintenance`,
      title: 'Bring forward scheduled fleet maintenance',
      type: 'EQUIPMENT',
      priority: 'HIGH',
      reason: `Equipment downtime accounts for ${round(ctx.downtimeDrag * 100, 1)}% modelled drag.`,
      impact: 'Addresses the downtime term of the drag model.',
      status: 'PROPOSED',
      basis: 'Rule-based: triggered when the downtime drag term exceeds 0.10.',
    })
  }
  if (ctx.blastingDrag > 0) {
    actions.push({
      id: `act-${mine.id}-blasting`,
      title: 'Recover development blasting schedule',
      type: 'BLASTING',
      priority: 'MEDIUM',
      reason: 'Weekly blast count is below the threshold assumed by the model.',
      impact: 'Addresses the blasting-readiness term of the drag model.',
      status: 'PROPOSED',
      basis: 'Rule-based: triggered when weekly blasts fall below 6.',
    })
  }
  if (actions.length === 0) {
    actions.push({
      id: `act-${mine.id}-none`,
      title: 'No corrective action indicated',
      type: 'NONE',
      priority: 'INFO',
      reason: 'All drag terms are below their action thresholds.',
      impact: 'Continue current plan.',
      status: 'INFO',
      basis: 'Rule-based.',
    })
  }
  return actions
}
