'use client'

import { useState } from 'react'
import type { Envelope } from '@/lib/provenance'

/**
 * Evidence primitives (PRD D-7 [D] P0, N-3 [D]).
 *
 * D-7 requires an evidence panel giving "inputs, model version, date,
 * uncertainty for any figure shown"; N-3 requires 100% of displayed numbers to
 * carry model version, input vintage and uncertainty.
 *
 * `Metric` is therefore the only way this console renders a number. It refuses
 * to display a bare value: if no envelope is supplied it says so, rather than
 * showing a number whose origin nobody can state.
 */

function fmtVintage(iso?: string | null): string {
  if (!iso) return 'unknown'
  const d = new Date(iso)
  if (Number.isNaN(d.getTime())) return String(iso)
  return `${d.toISOString().replace('T', ' ').slice(0, 16)} UTC`
}

function ageLabel(iso?: string | null): string | null {
  if (!iso) return null
  const t = new Date(iso).getTime()
  if (Number.isNaN(t)) return null
  const mins = Math.max(0, Math.round((Date.now() - t) / 60000))
  if (mins < 60) return `${mins} min old`
  const hrs = Math.round(mins / 60)
  if (hrs < 48) return `${hrs} h old`
  return `${Math.round(hrs / 24)} d old`
}

/** Source-kind badge. Colour and wording are driven by the envelope, never by the caller. */
export function SourceBadge({ env }: { env: Envelope<any> }) {
  const map: Record<string, { label: string; cls: string; title: string }> = {
    measured: {
      label: 'LIVE',
      cls: 'border-status-nominal/40 bg-status-nominal/10 text-status-nominal',
      title: 'Fetched this request from a real external service.',
    },
    derived: {
      label: 'DERIVED',
      cls: 'border-accent/40 bg-accent-muted text-accent',
      title: 'Computed deterministically from measured inputs.',
    },
    synthetic: {
      label: 'SYNTHETIC',
      cls: 'border-status-caution/40 bg-status-caution/10 text-status-caution',
      title:
        'Generated by the seeded synthetic model. MOIL operational data is proprietary (PRD §8.2). Not an observation.',
    },
    reference: {
      label: 'REFERENCE',
      cls: 'border-border-default bg-surface-1 text-text-tertiary',
      title: 'Fixed reference constant.',
    },
  }
  const m = map[env.source_kind] ?? map.reference
  return (
    <span
      title={m.title}
      className={`inline-flex items-center rounded-sm border px-1.5 py-0.5 font-mono text-xs font-medium tracking-wide ${m.cls}`}
    >
      {m.label}
    </span>
  )
}

export function EvidenceDetail({ env }: { env: Envelope<any> }) {
  return (
    <dl className="mt-2 space-y-1 border-t border-border-subtle pt-2 text-xs leading-relaxed">
      <div className="flex gap-2">
        <dt className="w-24 shrink-0 text-text-tertiary">Source</dt>
        <dd className="text-text-secondary">{env.source}</dd>
      </div>
      <div className="flex gap-2">
        <dt className="w-24 shrink-0 text-text-tertiary">Vintage</dt>
        <dd className="text-text-secondary">
          {fmtVintage(env.vintage)}
          {ageLabel(env.vintage) ? <span className="text-text-tertiary"> · {ageLabel(env.vintage)}</span> : null}
        </dd>
      </div>
      <div className="flex gap-2">
        <dt className="w-24 shrink-0 text-text-tertiary">Model</dt>
        <dd className="text-text-secondary">{env.model_version ?? 'not modelled'}</dd>
      </div>
      <div className="flex gap-2">
        <dt className="w-24 shrink-0 text-text-tertiary">Uncertainty</dt>
        <dd className="text-text-secondary">
          {env.uncertainty
            ? `±${env.uncertainty.plus_minus} (${Math.round(env.uncertainty.confidence * 100)}%) — ${env.uncertainty.basis}`
            : 'not quantified'}
        </dd>
      </div>
      {env.method ? (
        <div className="flex gap-2">
          <dt className="w-24 shrink-0 text-text-tertiary">Method</dt>
          <dd className="text-text-secondary">{env.method}</dd>
        </div>
      ) : null}
    </dl>
  )
}

export interface MetricProps {
  label: string
  /** The provenance envelope. Omit only when the value is genuinely unavailable. */
  env?: Envelope<any> | null
  /** Override the rendered value (e.g. pre-formatted); defaults to `env.value`. */
  display?: string | number | null
  unit?: string
  /** Shown when there is no value — states why, never a placeholder number. */
  unavailableReason?: string
  emphasis?: boolean
}

/**
 * The only number-rendering component in the console.
 *
 * No envelope → no number. That is deliberate: it makes an unprovenanced
 * figure impossible to ship by accident.
 */
export function Metric({ label, env, display, unit, unavailableReason, emphasis }: MetricProps) {
  const [open, setOpen] = useState(false)
  const value = display ?? env?.value ?? null
  const hasValue = value !== null && value !== undefined && value !== ''

  return (
    <div className="rounded-md border border-border-default bg-surface-2 p-3">
      <div className="flex items-start justify-between gap-2">
        <span className="label">{label}</span>
        {env ? <SourceBadge env={env} /> : null}
      </div>

      {hasValue ? (
        <div
          data-metric
          className={`mt-1 font-mono ${emphasis ? 'text-2xl' : 'text-lg'} text-text-primary`}
        >
          {typeof value === 'number' ? value.toLocaleString() : value}
          {unit ? <span className="ml-1 text-xs text-text-secondary">{unit ?? env?.unit}</span> : null}
        </div>
      ) : (
        <div className="mt-1 text-sm text-text-tertiary">
          <span className="font-mono">unavailable</span>
          {unavailableReason ? (
            <p className="mt-1 text-xs leading-snug text-text-tertiary">{unavailableReason}</p>
          ) : null}
        </div>
      )}

      {env ? (
        <>
          <button
            type="button"
            onClick={() => setOpen((v) => !v)}
            aria-expanded={open}
            className="mt-2 rounded-sm font-mono text-xs tracking-wide text-text-tertiary transition-colors duration-[120ms] ease-out hover:text-text-secondary"
          >
            {open ? '− evidence' : '+ evidence'}
          </button>
          {open ? <EvidenceDetail env={env} /> : null}
        </>
      ) : hasValue ? (
        // A value with no envelope must not pass silently — N-3 is 100%.
        <p className="mt-2 text-xs text-status-critical">No provenance attached (PRD N-3 violation).</p>
      ) : null}
    </div>
  )
}

/** Dataset-level banner (PRD N-6): staleness and degradation, stated plainly. */
export function IntegrityBanner({
  integrity,
}: {
  integrity?: {
    contains_synthetic: boolean
    live_sources_ok: boolean
    degraded_reason: string | null
    staleness_seconds: number | null
    notice: string
  } | null
}) {
  if (!integrity) return null
  const degraded = !integrity.live_sources_ok
  return (
    <div
      role="status"
      className={`rounded-md border px-3 py-2 text-xs leading-relaxed ${
        degraded
          ? 'border-status-critical/40 bg-status-critical/10 text-text-primary'
          : integrity.contains_synthetic
            ? 'border-status-caution/40 bg-status-caution/10 text-text-primary'
            : 'border-status-nominal/40 bg-status-nominal/10 text-text-primary'
      }`}
    >
      {integrity.notice}
      {integrity.degraded_reason ? (
        <span className="mt-1 block font-mono text-xs text-text-secondary">
          reason: {integrity.degraded_reason}
        </span>
      ) : null}
      {integrity.staleness_seconds != null ? (
        <span className="mt-1 block font-mono text-xs text-text-secondary">
          freshest measured input: {Math.round(integrity.staleness_seconds / 3600)} h old
        </span>
      ) : null}
    </div>
  )
}
