import { readFile } from 'node:fs/promises'
import path from 'node:path'

export interface ImageryRecord {
  file: string
  bytes: number
  collection: string
  scene_id: string
  mgrs_tile: string
  datetime: string
  eo_cloud_cover_pct: number | null
  platform: string | null
  processing: string
  source: string
}

export interface ImageryManifest {
  bbox: number[]
  search_window: string
  note: string
  images: ImageryRecord[]
}

/**
 * The imagery manifest, read on the server.
 *
 * Generated by `python -m app.ml.fetch_identity_imagery`. Returns null when it
 * has not been run — in which case nothing is drawn rather than something else
 * being drawn in its place.
 */
export async function loadImagery(): Promise<ImageryManifest | null> {
  try {
    const file = path.join(process.cwd(), 'public', 'imagery', '_provenance.json')
    return JSON.parse(await readFile(file, 'utf8')) as ImageryManifest
  } catch {
    return null
  }
}

/**
 * A band of real Sentinel-2 imagery of the ground this product is about.
 *
 * Identity, not decoration, and the distinction is the caption: each frame
 * names its scene, its date and its cloud cover, so it is evidence of the study
 * area rather than an impression of one. No stock photography and no
 * illustrative space art — an invented image of a place is the same class of
 * claim as an invented number about it.
 */
export function BeltImagery({ manifest }: { manifest: ImageryManifest }) {
  return (
    <section
      className="border-t border-border-subtle py-14 sm:py-20"
      data-provenance="measured"
    >
      <h2 className="label">The ground this is about</h2>
      <p className="measure mt-3 text-sm text-text-secondary">
        Sentinel-2 L2A over the Central India manganese belt — the same bounds the
        prospectivity surface scores. Real scenes, named below, not illustration.
      </p>

      <div className="mt-8 grid gap-4 sm:grid-cols-3">
        {manifest.images.map((img) => (
          <figure key={img.scene_id} className="min-w-0">
            <div className="overflow-hidden rounded-md border border-border-default bg-surface-1">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={img.file}
                alt={`Sentinel-2 true-colour scene ${img.mgrs_tile} over the Central India manganese belt, ${img.datetime.slice(0, 10)}`}
                width={512}
                height={512}
                loading="lazy"
                decoding="async"
                className="block aspect-square w-full object-cover"
              />
            </div>
            <figcaption className="mt-2 font-mono text-xs leading-relaxed text-text-tertiary">
              {img.mgrs_tile} · {img.datetime.slice(0, 10)} · cloud{' '}
              {img.eo_cloud_cover_pct === null ? 'unknown' : `${img.eo_cloud_cover_pct.toFixed(2)}%`}
              <br />
              {img.scene_id}
            </figcaption>
          </figure>
        ))}
      </div>

      <p className="measure mt-6 text-xs text-text-tertiary">
        {manifest.images[0]?.processing}. Source: {manifest.images[0]?.source}.{' '}
        {manifest.note} Regenerate with{' '}
        <code className="font-mono">python -m app.ml.fetch_identity_imagery</code>.
      </p>
    </section>
  )
}
