'use client'

import { useRef } from 'react'
import gsap from 'gsap'
import { ScrollTrigger } from 'gsap/ScrollTrigger'
import { useGSAP } from '@gsap/react'

gsap.registerPlugin(ScrollTrigger, useGSAP)

export interface StackLayer {
  id: string
  name: string
  source_kind: string
  source: string
  note: string
}

export interface StackData {
  model_version: string
  validation: string
  lomo_auc: number
  bounds: { minY: number; maxY: number; minX: number; maxX: number }
  layers: StackLayer[]
  points: { x: number; y: number; label: number; iron_oxide: number; slope_deg: number; ndvi: number }[]
  cells: { x: number; y: number; p: number; sd: number }[]
}

/**
 * The landing page's one persistent visual anchor.
 *
 * Three layers of real pipeline output, stacked and then separated as the page
 * scrolls: the points the model was fitted on, the kriged surface over them,
 * and the spread around that surface. Scrolling moves between them; the text
 * beside each one is an annotation, not a paragraph.
 *
 * WHAT IS AND IS NOT HERE
 * -----------------------
 * Every mark is drawn from `public/data/prospectivity-stack.json`, generated by
 * `python -m app.ml.export_stack` from the loaded honest model — 1,710 kriged
 * cells and the 50 measured training points. There is no Sentinel-2 imagery
 * layer because this pipeline does not mosaic L2A scenes for the belt, and an
 * invented raster is exactly the thing the rest of this work removed.
 *
 * MOTION RULES
 * ------------
 * Transform and opacity only, so nothing here triggers layout. Native scroll —
 * no scroll hijacking, no smooth-scroll shim. `gsap.matchMedia()` gates the
 * effect: below 768px, and under `prefers-reduced-motion`, the layers render
 * separated and static rather than animating. The markup is complete before any
 * script runs, so the content is in the HTML and the animation only moves what
 * is already there.
 *
 * No count-ups: a number that spins up to its value is theatre applied to a
 * measurement. No looping pulses: a pulsing dot reads as a live feed, and none
 * of this is live.
 */
export function ProspectivityStack({ data }: { data: StackData }) {
  const root = useRef<HTMLDivElement>(null)

  useGSAP(
    () => {
      const mm = gsap.matchMedia()

      mm.add(
        {
          motion: '(min-width: 768px) and (prefers-reduced-motion: no-preference)',
          still: '(max-width: 767px), (prefers-reduced-motion: reduce)',
        },
        (ctx) => {
          const { motion } = ctx.conditions as { motion: boolean; still: boolean }
          const layers = gsap.utils.toArray<HTMLElement>('[data-stack-layer]', root.current)

          if (!motion) {
            // Static, separated, legible. The page must work without motion.
            layers.forEach((el, i) => {
              gsap.set(el, { yPercent: i * 6, opacity: 1 })
            })
            return
          }

          // Start stacked, flat on top of one another.
          layers.forEach((el, i) => {
            gsap.set(el, { yPercent: 0, scale: 1, opacity: i === 0 ? 1 : 0.35 })
          })

          // The signature moment, and the only one: the stack separates.
          gsap
            .timeline({
              scrollTrigger: {
                trigger: root.current,
                start: 'top 70%',
                end: 'bottom 60%',
                scrub: 0.6,
              },
            })
            .to(layers, {
              yPercent: (i: number) => -i * 13,
              scale: (i: number) => 1 - i * 0.03,
              opacity: 1,
              ease: 'none',
              stagger: 0.04,
            })

          // Annotations arrive with their layer. Opacity and a small lift only.
          //
          // `immediateRender: false` matters more than it looks: without it a
          // `.from({opacity: 0})` applies the start state the moment the
          // tween is built, so every annotation is invisible until its trigger
          // fires — and if the trigger never fires, the text is simply gone.
          // Caught in the 1280px capture, where the whole annotation column
          // rendered blank. The content is in the HTML; motion must not be able
          // to take it away.
          gsap.utils.toArray<HTMLElement>('[data-stack-note]', root.current).forEach((note) => {
            gsap.from(note, {
              opacity: 0,
              y: 12,
              duration: 0.5,
              ease: 'power2.out',
              immediateRender: false,
              scrollTrigger: { trigger: note, start: 'top 90%', once: true },
            })
          })
        }
      )

      return () => mm.revert()
    },
    { scope: root }
  )

  const { bounds } = data
  const W = 520
  const H = 340
  const px = (x: number) => ((x - bounds.minX) / (bounds.maxX - bounds.minX)) * W
  const py = (y: number) => H - ((y - bounds.minY) / (bounds.maxY - bounds.minY)) * H

  // cividis, the project's sequential colormap — a score is a quantity, not a state.
  const cividis = (t: number) => {
    const stops = [
      [0, 32, 76], [0, 42, 102], [0, 52, 110], [39, 63, 108], [60, 74, 107],
      [87, 100, 109], [126, 130, 111], [167, 162, 106], [217, 199, 87],
    ]
    const i = Math.min(stops.length - 2, Math.max(0, Math.floor(t * (stops.length - 1))))
    const f = t * (stops.length - 1) - i
    const c = stops[i].map((v, k) => Math.round(v + (stops[i + 1][k] - v) * f))
    return `rgb(${c[0]},${c[1]},${c[2]})`
  }

  const maxSd = Math.max(...data.cells.map((c) => c.sd), 0.0001)

  return (
    <div ref={root} className="grid gap-10 lg:grid-cols-[minmax(0,1fr)_minmax(0,22rem)] lg:gap-16">
      {/* The anchor. One object, three layers. */}
      <div className="relative mx-auto w-full max-w-[560px]">
        <svg
          viewBox={`0 0 ${W} ${H + 90}`}
          className="w-full"
          role="img"
          aria-label={`Three layers of Track A output over the Madhya Pradesh and Maharashtra manganese belt: ${data.points.length} measured points, a kriged prospectivity surface of ${data.cells.length} cells, and the kriging uncertainty for the same cells.`}
        >
          <title>Track A data stack</title>

          {/* Layer 3 (back): kriging uncertainty */}
          <g data-stack-layer="spread" style={{ transformOrigin: '50% 50%' }}>
            <rect x="0" y="0" width={W} height={H} fill="var(--color-surface-1)" opacity="0.5" rx="6" />
            {data.cells.map((c, i) => (
              <rect
                key={`u${i}`}
                x={px(c.x) - 3}
                y={py(c.y) - 3}
                width="6"
                height="6"
                fill="var(--color-text-tertiary)"
                opacity={Math.min(0.85, (c.sd / maxSd) * 0.85)}
              />
            ))}
          </g>

          {/* Layer 2 (middle): the kriged prospectivity surface */}
          <g data-stack-layer="surface" style={{ transformOrigin: '50% 50%' }}>
            <rect x="0" y="0" width={W} height={H} fill="var(--color-surface-1)" opacity="0.5" rx="6" />
            {data.cells.map((c, i) => (
              <rect
                key={`p${i}`}
                x={px(c.x) - 3}
                y={py(c.y) - 3}
                width="6"
                height="6"
                fill={cividis(c.p)}
                opacity="0.9"
              />
            ))}
          </g>

          {/* Layer 1 (front): the measured points the model was fitted on */}
          <g data-stack-layer="measured" style={{ transformOrigin: '50% 50%' }}>
            {data.points.map((p, i) => (
              <circle
                key={`m${i}`}
                cx={px(p.x)}
                cy={py(p.y)}
                r={p.label === 1 ? 4.5 : 3}
                fill={p.label === 1 ? 'var(--color-accent)' : 'none'}
                stroke={p.label === 1 ? 'none' : 'var(--color-text-tertiary)'}
                strokeWidth="1.2"
              />
            ))}
          </g>
        </svg>
      </div>

      {/* Annotation, not prose. */}
      <ol className="space-y-8 lg:pt-6">
        {data.layers.map((l, i) => (
          <li key={l.id} data-stack-note className="border-l border-border-strong pl-4">
            <div className="flex items-baseline gap-3">
              <span className="font-mono text-xs tabular-nums text-text-tertiary">
                {String(i + 1).padStart(2, '0')}
              </span>
              <h3 className="text-base font-semibold text-text-primary">{l.name}</h3>
            </div>
            <p className="measure mt-2 text-sm text-text-secondary">{l.note}</p>
            <p className="mt-2 font-mono text-xs text-text-tertiary">{l.source}</p>
          </li>
        ))}
      </ol>
    </div>
  )
}
