/**
 * Provenance envelope — Nakshatra-X integrity layer.
 *
 * Every number surfaced by the API carries where it came from, how old it is,
 * how uncertain it is, and whether it is measured or synthetic. The UI renders
 * these fields; nothing is allowed to appear as a bare number.
 *
 * Integrity rule: `is_live` is true ONLY for values fetched from a real
 * external service during this request. Anything generated locally is
 * `is_synthetic: true` and must never be labelled LIVE.
 */

/** Where a value came from. */
export type SourceKind =
  /** Fetched this request from a real external API. */
  | 'measured'
  /** Deterministically derived from measured inputs (no new information). */
  | 'derived'
  /** Generated by the calibrated synthetic operational-data model. */
  | 'synthetic'
  /** A fixed reference constant (mine coordinates, statutory limits). */
  | 'reference'

export interface Uncertainty {
  /** Half-width of the interval, in the same unit as `value`. */
  plus_minus: number
  /** Nominal coverage of the interval, e.g. 0.8 for an 80% interval. */
  confidence: number
  /** How the interval was obtained. */
  basis: string
}

export interface Envelope<T = number> {
  value: T
  unit: string
  /** Human-readable origin, e.g. "Open-Meteo Forecast API v1". */
  source: string
  source_kind: SourceKind
  /** ISO-8601 timestamp the underlying data is valid for. */
  vintage: string
  /** Identifier of the code/model that produced it, or null if not modelled. */
  model_version: string | null
  uncertainty: Uncertainty | null
  is_synthetic: boolean
  is_live: boolean
  /** Optional one-line explanation of the method, shown in the evidence panel. */
  method?: string
}

export interface EnvelopeInit<T> {
  value: T
  unit: string
  source: string
  source_kind: SourceKind
  vintage?: string
  model_version?: string | null
  uncertainty?: Uncertainty | null
  method?: string
}

/**
 * Build an envelope. `is_synthetic` and `is_live` are computed from
 * `source_kind` rather than passed in, so a caller cannot mislabel synthetic
 * data as live.
 */
export function envelope<T>(init: EnvelopeInit<T>): Envelope<T> {
  return {
    value: init.value,
    unit: init.unit,
    source: init.source,
    source_kind: init.source_kind,
    vintage: init.vintage ?? new Date().toISOString(),
    model_version: init.model_version ?? null,
    uncertainty: init.uncertainty ?? null,
    is_synthetic: init.source_kind === 'synthetic',
    is_live: init.source_kind === 'measured',
    method: init.method,
  }
}

/** A measured value obtained from a live external service. */
export function measured<T>(
  value: T,
  unit: string,
  source: string,
  opts: Partial<EnvelopeInit<T>> = {}
): Envelope<T> {
  return envelope({ ...opts, value, unit, source, source_kind: 'measured' })
}

/** A value computed deterministically from measured inputs. */
export function derived<T>(
  value: T,
  unit: string,
  source: string,
  opts: Partial<EnvelopeInit<T>> = {}
): Envelope<T> {
  return envelope({ ...opts, value, unit, source, source_kind: 'derived' })
}

/** A value produced by the synthetic operational-data generator. */
export function synthetic<T>(
  value: T,
  unit: string,
  source: string,
  opts: Partial<EnvelopeInit<T>> = {}
): Envelope<T> {
  return envelope({ ...opts, value, unit, source, source_kind: 'synthetic' })
}

/** A fixed reference constant. */
export function reference<T>(
  value: T,
  unit: string,
  source: string,
  opts: Partial<EnvelopeInit<T>> = {}
): Envelope<T> {
  return envelope({ ...opts, value, unit, source, source_kind: 'reference' })
}

/** Dataset-level banner describing the mix of sources in a response. */
export interface DataIntegrity {
  /** True if any field in the payload is synthetic. */
  contains_synthetic: boolean
  /** True if the live upstream fetch succeeded this request. */
  live_sources_ok: boolean
  /** Populated when a live fetch failed and synthetic values stood in. */
  degraded_reason: string | null
  /** Age of the freshest measured input, in seconds; null if none. */
  staleness_seconds: number | null
  notice: string
}

export function dataIntegrity(args: {
  containsSynthetic: boolean
  liveOk: boolean
  degradedReason?: string | null
  stalenessSeconds?: number | null
}): DataIntegrity {
  const { containsSynthetic, liveOk } = args
  let notice: string
  if (!liveOk) {
    notice =
      'DEGRADED — live upstream unavailable. Displayed values are synthetic and must not be read as observations.'
  } else if (containsSynthetic) {
    notice =
      'MIXED — weather is measured live; operational figures are synthetic (MOIL operational data is proprietary) and are labelled per field.'
  } else {
    notice = 'All displayed values are measured or derived from measured inputs.'
  }
  return {
    contains_synthetic: containsSynthetic,
    live_sources_ok: liveOk,
    degraded_reason: args.degradedReason ?? null,
    staleness_seconds: args.stalenessSeconds ?? null,
    notice,
  }
}
